// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
/** @type {import("c3ide2-types").Theme} */
const Config = {
  addonType: "theme",
  id: "<@ADDON_ID>",
  name: "<@ADDON_NAME>",
  version: "1.0.0.0",
  author: "<@ADDON_AUTHOR>",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Description",
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  stylesheets: ["theme.css"],
};

module.exports = Config;